package org.base;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

public class AutoRegister {
public static void main(String[] args) throws AWTException {
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\$AM$ANKAR\\eclipse-workspace\\MyProjectInSelenium\\Driver\\chromedriver.exe");
	WebDriver driver = new ChromeDriver();
	driver.get("https://demo.automationtesting.in/Register.html");
	driver.manage().window().maximize();
	WebElement firstname = driver.findElement(By.xpath("//input[@placeholder='First Name']"));
	Actions act = new Actions(driver);
	act.click(firstname).perform();
	Robot r = new Robot();
	r.keyPress(KeyEvent.VK_S);
	r.keyRelease(KeyEvent.VK_S);
	r.keyPress(KeyEvent.VK_A);
	r.keyRelease(KeyEvent.VK_A);
	r.keyPress(KeyEvent.VK_M);
	r.keyRelease(KeyEvent.VK_M);
	WebElement lastname = driver.findElement(By.xpath("//input[@placeholder='Last Name']"));
	act.click(lastname).perform();
	r.keyPress(KeyEvent.VK_S);
	r.keyRelease(KeyEvent.VK_S);
	r.keyPress(KeyEvent.VK_A);
	r.keyRelease(KeyEvent.VK_A);
	r.keyPress(KeyEvent.VK_N);
	r.keyRelease(KeyEvent.VK_N);
	r.keyPress(KeyEvent.VK_K);
	r.keyRelease(KeyEvent.VK_K);
	r.keyPress(KeyEvent.VK_A);
	r.keyRelease(KeyEvent.VK_A);
	r.keyPress(KeyEvent.VK_R);
	r.keyRelease(KeyEvent.VK_R);
	WebElement address = driver.findElement(By.xpath("//textarea[@ng-model='Adress']"));
	act.click(address).perform();
	r.keyPress(KeyEvent.VK_1);
	r.keyRelease(KeyEvent.VK_1);
	r.keyPress(KeyEvent.VK_0);
	r.keyRelease(KeyEvent.VK_0);
	r.keyPress(KeyEvent.VK_SPACE);
	r.keyRelease(KeyEvent.VK_SPACE);
	r.keyPress(KeyEvent.VK_M);
	r.keyRelease(KeyEvent.VK_M);
	r.keyPress(KeyEvent.VK_G);
	r.keyRelease(KeyEvent.VK_G);
	r.keyPress(KeyEvent.VK_R);
	r.keyRelease(KeyEvent.VK_R);
	r.keyPress(KeyEvent.VK_SPACE);
	r.keyRelease(KeyEvent.VK_SPACE);
	r.keyPress(KeyEvent.VK_S);
	r.keyRelease(KeyEvent.VK_S);
	r.keyPress(KeyEvent.VK_T);
	r.keyRelease(KeyEvent.VK_T);
	r.keyPress(KeyEvent.VK_R);
	r.keyRelease(KeyEvent.VK_R);
	r.keyPress(KeyEvent.VK_E);
	r.keyRelease(KeyEvent.VK_E);
	r.keyPress(KeyEvent.VK_E);
	r.keyRelease(KeyEvent.VK_E);
	r.keyPress(KeyEvent.VK_T);
	r.keyRelease(KeyEvent.VK_T);
	r.keyPress(KeyEvent.VK_SPACE);
	r.keyRelease(KeyEvent.VK_SPACE);
	r.keyPress(KeyEvent.VK_C);
	r.keyRelease(KeyEvent.VK_C);
	r.keyPress(KeyEvent.VK_H);
	r.keyRelease(KeyEvent.VK_H);
	r.keyPress(KeyEvent.VK_E);
	r.keyRelease(KeyEvent.VK_E);
	r.keyPress(KeyEvent.VK_N);
	r.keyRelease(KeyEvent.VK_N);
	r.keyPress(KeyEvent.VK_N);
	r.keyRelease(KeyEvent.VK_N);
	r.keyPress(KeyEvent.VK_A);
	r.keyRelease(KeyEvent.VK_A);
	r.keyPress(KeyEvent.VK_I);
	r.keyRelease(KeyEvent.VK_I);
	r.keyPress(KeyEvent.VK_PERIOD);
	r.keyRelease(KeyEvent.VK_PERIOD);
	r.keyPress(KeyEvent.VK_6);
	r.keyRelease(KeyEvent.VK_6);
	r.keyPress(KeyEvent.VK_8);
	r.keyRelease(KeyEvent.VK_8);
	WebElement email = driver.findElement(By.xpath("//input[@ng-model='EmailAdress']"));
	act.click(email).perform();
	r.keyPress(KeyEvent.VK_S);
	r.keyRelease(KeyEvent.VK_S);
	r.keyPress(KeyEvent.VK_A);
	r.keyRelease(KeyEvent.VK_A);
	r.keyPress(KeyEvent.VK_M);
	r.keyRelease(KeyEvent.VK_M);
	r.keyPress(KeyEvent.VK_1);
	r.keyRelease(KeyEvent.VK_1);
	r.keyPress(KeyEvent.VK_2);
	r.keyRelease(KeyEvent.VK_2);
	r.keyPress(KeyEvent.VK_3);
	r.keyRelease(KeyEvent.VK_3);
	r.keyPress(KeyEvent.VK_PERIOD);
	r.keyRelease(KeyEvent.VK_PERIOD);
	r.keyPress(KeyEvent.VK_G);
	r.keyRelease(KeyEvent.VK_G);
	r.keyPress(KeyEvent.VK_M);
	r.keyRelease(KeyEvent.VK_M);
	r.keyPress(KeyEvent.VK_A);
	r.keyRelease(KeyEvent.VK_A);
	r.keyPress(KeyEvent.VK_I);
	r.keyRelease(KeyEvent.VK_I);
	r.keyPress(KeyEvent.VK_L);
	r.keyRelease(KeyEvent.VK_L);
	r.keyPress(KeyEvent.VK_PERIOD);
	r.keyRelease(KeyEvent.VK_PERIOD);
	r.keyPress(KeyEvent.VK_C);
	r.keyRelease(KeyEvent.VK_C);
	r.keyPress(KeyEvent.VK_O);
	r.keyRelease(KeyEvent.VK_O);
	r.keyPress(KeyEvent.VK_M);
	r.keyRelease(KeyEvent.VK_M);
	WebElement phone = driver.findElement(By.xpath("//input[@ng-model='Phone']"));
	act.click(phone).perform();
	r.keyPress(KeyEvent.VK_9);
	r.keyRelease(KeyEvent.VK_9);
	r.keyPress(KeyEvent.VK_8);
	r.keyRelease(KeyEvent.VK_8);
	r.keyPress(KeyEvent.VK_7);
	r.keyRelease(KeyEvent.VK_7);
	r.keyPress(KeyEvent.VK_6);
	r.keyRelease(KeyEvent.VK_6);
	r.keyPress(KeyEvent.VK_5);
	r.keyRelease(KeyEvent.VK_5);
	r.keyPress(KeyEvent.VK_4);
	r.keyRelease(KeyEvent.VK_4);
	r.keyPress(KeyEvent.VK_3);
	r.keyRelease(KeyEvent.VK_3);
	r.keyPress(KeyEvent.VK_2);
	r.keyRelease(KeyEvent.VK_2);
	r.keyPress(KeyEvent.VK_1);
	r.keyRelease(KeyEvent.VK_1);
	r.keyPress(KeyEvent.VK_0);
	r.keyRelease(KeyEvent.VK_0);
	
}
}
